---
- name: Create directory for docker files and container data
  file:
    path: "{{ docker_project_path }}"
    state: directory
- name: Copy the dockerfile
  copy:
    src: "{{ httpd_dockerfile }}"
    dest: "{{ docker_project_path }}" 
- name: Copy the "{{ document_root }}" directory
  copy:
    src: "{{ document_root }}"
    dest: "{{ docker_project_path }}"
- name: Build the container
  command: docker build -t "{{ docker_container_name }}" "{{ docker_project_path }}"
- name: Run the container
  command: docker run -d -p 80:80 -t "{{ docker_container_name }}"

