---
- name: Disable SELinux
  selinux:
    state: disabled
- name: Add docker-ce repository
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: "{{ base_url_docker }}"
    gpgkey: "{{ gpg_key_docker }}"
    gpgcheck: yes
    file: docker
- name: Install docker
  yum:
    name: docker
    state: latest
  register: docke_install
- name: Enable Docker service start at boot
  service:
    name: docker
    enabled: yes
- name: Add IPs to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ etc_hosts_github }}"
    state: present
- name: Restart host
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  when: docke_install.changed
- name: Wait for server to restart
  wait_for_connection:
    delay: 60
    timeout: 300
  when: docke_install.changed
